### ISSUE TITLE
can not register with azure mobile hub

### ISSUE THREAD

**Issue by shalinasanga** [Azure/azure-mobile-apps#52]
Configured all thing as per document and sample.
Token registering with azure fails.
`MobileServiceClient client = new MobileServiceClient("Endpoint=sb://REST OF THE DefaultListenSharedAccessSignature");`

This throws error invalid Uri. If i change first section of url to https, says 'Unauthorized'

i am using 'Microsoft.Azure.Mobile.Client' latest 4.0.2

**Comment by guperrot** [comment]
On what platform are you running the project (Xamarin.iOS, Xamarin.Android or UWP)? Do you get the error on more than 1 platform?

**Comment by shalinasanga** [comment]
ohh..i see now, this docs are confusing. 
Can i use my .Net back end server project instead of Azure Mobile Apps instance in azure ? 
if 'yes' How ?

**Comment by jwallra** [comment]
It doesn't really make any sense to bring your own backend in Mobile Apps.  Our client and server SDKs are designed to work together.  It's theoretically possible to use your own backend, but you'd have to basically reinvent the wheel for how it communicates with the client.  I would highly recommend using the Mobile Apps backend server solution.

**Comment by shalinasanga** [comment]
Thank you for your advice, but what i exactly need is, directly communicate(send messages) to Azure notification hub from my .Net backend. Then Azure notification hub can send them to corresponding push notification servers and Xamarin.Forms mobile app will receive them.
I have already implemented and using .Net backend project with xamarin mobile app. So all the detail logic are in backend. if something changes in DB i want to send them to Notification hub with device notification token and app will receive them.
Can i do this ?

**Comment by guperrot** [comment]
You can call Notification Hub REST API directly to push anything to devices to achieve that if I understand correctly.

**Comment by shalinasanga** [comment]
Yes, i need to directly communicate with Azure notification hub from my hosted .Net backend. This documentation lacks that part, even its really hard to find detailed documentation regarding this. Most of the developers/Companies use their own hosted backends.
If you guys can provide detail explanation of what nuget packages should use and how to use on our own backend that will be great.
something like this[https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-aspnet-backend-android-xplat-segmented-gcm-push-notification#send-tagged-notifications](url)

**Comment by guperrot** [comment]
Notification hubs called from a server is covered in this documentation page: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-backend-how-to-use-server-sdk#how-to-add-push-notifications-to-a-server-project

**Comment by guperrot** [comment]
Hey! 

We haven’t heard from you in a while, so I am going to go ahead and close this ticket. Should you still have any questions, you can reply here & we will reopen the ticket; or if you prefer you can create a new ticket. Please don’t hesitate to contact us again.
